version: '2'
services:
  php:
    user: root
    build: ./
    volumes:
      - ./config:/var/www/config
      - ./views:/var/www/views
      - ./models:/var/www/models
      - ./controllers:/var/www/controllers
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./web/index.php:/var/www/html/index.php
      - ./.env:/var/www/.env
    ports:
      - '8000:80'
  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
volumes:
  mariadb-data: