version: '2'
services:

  webdriver: 
    image: selenium/standalone-firefox:2.53.0
    ports:
      - "4444:4444"
    networks:
      - app-compose-network

  php:
    user: root
    build: ./
    volumes:
      - ./assets:/var/www/assets
      - ./config:/var/www/config
      - ./views:/var/www/views
      - ./models:/var/www/models
      - ./controllers:/var/www/controllers
      - ./tests:/var/www/tests
      - ./messages:/var/www/messages
      - ./migrations:/var/www/migrations
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./web/index.php:/var/www/html/index.php
      - ./web/css/custom_view.css:/var/www/html/css/custom_view.css
      - ./.env:/var/www/.env
    ports:
      - '8000:80'
    networks:
      - app-compose-network
      
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: hospital
      # You should definitely change the password in production
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

    networks:
      - app-compose-network

    volumes:
      - db-data:/var/lib/postgresql/data:rw

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin@admin.com"
    ports:
      - "16543:80"
    depends_on:
      - database
    networks:
      - app-compose-network      
networks: 
  app-compose-network:
    driver: bridge

volumes:
  db-data: